config/routes.rb
  post '/bounces' => 'amazon_bounces#notification'

  get "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  get "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  get "/change_locale" => "i18n#change_locale", :as => :change_locale

  post '/after_ship/webhook' => 'after_ships#webhook'

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    resources :listings, only: [], defaults: { format: :json } do
      member do
        post :update_working_time_slots
      end
    end
  end

  match '/harmony_proxy/*harmony_path' => 'harmony_proxy#proxy', via: :all

  get "/ui_api/topbar_props" => "topbar_api#props"

  get '/_lp_preview' => 'landing_page#preview', as: :landing_page_preview

  locale_regex_string = Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(Sharetribe::REMOVED_LOCALES.to_a).join("|")
  locale_matcher = Regexp.new(locale_regex_string)
  locale_matcher_anchored = Regexp.new("^(#{locale_regex_string})$")

  get '/:locale/' => 'landing_page#index', as: :landing_page_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/' => 'landing_page#index', as: :landing_page_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  get '/:locale/s' => 'homepage#index', as: :search_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/s' => 'homepage#index', as: :search_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  post '/search_listing' => 'homepage#auto_complete_search', as: :auto_complete_search
  get '/search_listing_by_name' => 'listings#search_by_name', as: :search_by_name
  post '/add_packing_dimension' => 'listings#add_packing_dimension', as: :add_packing_dimension

  get '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  get '/' => 'homepage#index', as: :homepage_without_locale
  get '/:locale/s', to: redirect('/%{locale}', status: 307), constraints: { locale: locale_matcher }
  get '/s', to: redirect('/', status: 307)

  get '/500' => 'errors#server_error'
  get '/404' => 'errors#not_found', :as => :error_not_found
  get '/406' => 'errors#not_acceptable', :as => :error_not_acceptable
  get '/410' => 'errors#gone', as: :error_gone
  get '/community_not_found' => 'errors#community_not_found', as: :community_not_found
  get '/not_available' => 'application#not_available', as: :community_not_available

  get '/load_cart', to: 'listings#load_cart'

  resources :communities, only: [:new, :create]

  devise_for :people, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "omniauth" }

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do
    get '/cart', to: 'listings#cart'

    put '/mercury_update' => "mercury_update#update", :as => :mercury_update

    get "/transactions/op_status/:process_token" => "paypal_service/checkout_orders#paypal_op_status", as: :paypal_op_status
    get "/transactions/transaction_op_status/:process_token" => "transactions#transaction_op_status", :as => :transaction_op_status
    get "/transactions/created/:transaction_id" => "transactions#created", as: :transaction_created
    get "/transactions/finalize_processed/:process_token" => "transactions#finalize_processed", as: :transaction_finalize_processed

    get "/transactions/new" => "transactions#new", as: :new_transaction
    get "/transactions/:uuid/checkout" => "transactions#checkout", as: :checkout_transaction
    get "/transactions/:uuid/shipment" => "transactions#shipment", as: :shipment_transaction
    get "/transactions/:uuid/change_shipping_selection" => "transactions#change_shipping_selection", as: :change_shipping_selection_transaction
    get "/transactions/:uuid/update_promo_code" => "transactions#update_promo_code", as: :update_promo_code_transaction
    get "/transactions/:uuid/change_state_shipping_form" => "transactions#change_state_shipping_form", as: :change_state_shipping_form
    get "/transactions/:uuid/payment" => "transactions#payment", as: :payment_transaction
    get "/transactions/:uuid/thank_you" => "transactions#thank_you", as: :thank_you_transaction
    post "/transactions/:transaction_id/pay_order" => "transaction_addresses#pay_order", as: :pay_order_transaction

    get "/listings/:listing_id/book", :to => redirect { |params, request|
      "/#{params[:locale]}/listings/#{params[:listing_id]}/initiate?#{request.query_string}"
    }
    post "/listings/:listing_id/booked"    => "preauthorize_transactions#initiated", as: :booked # POST request, no redirect

    get "/listings/:listing_id/initiate"   => "preauthorize_transactions#initiate", :as => :initiate_order
    post "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    post "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    get "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    get "/logout" => "sessions#destroy", :as => :logout
    get "/confirmation_pending" => "community_memberships#confirmation_pending", :as => :confirmation_pending
    get "/login" => "sessions#new", :as => :login
    get "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    get "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    get '/:person_id/settings/payments' => 'payment_settings#index', :as => :person_payment_settings
    post '/:person_id/settings/payments' => 'payment_settings#create', :as => :create_person_payment_settings
    put '/:person_id/settings/payments' => 'payment_settings#update', :as => :update_person_payment_settings
    get '/:person_id/settings/payments/paypal_account' => 'paypal_accounts#index', :as => :paypal_account_settings_payment

    get  '/community_memberships/pending_consent' => 'community_memberships#pending_consent', as: :pending_consent
    post '/community_memberships/give_consent'    => 'community_memberships#give_consent', as: :give_consent
    get  '/community_memberships/access_denied'   => 'community_memberships#access_denied', as: :access_denied

    get  '/community_memberships/check_email_availability_and_validity' => 'community_memberships#check_email_availability_and_validity'
    get  '/community_memberships/check_invitation_code'                 => 'community_memberships#check_invitation_code'

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    get "/categories", :to => redirect { |params, request|
      "/#{params[:locale]}/rent/#{request[:category]}/#{request[:subcategories]}/#{request[:children_categories]}"
    }

    get "rent/:category_name/:subcategory_name", to: "categories#index"
    get "rent/:category_name/:subcategory_name/:childcategory_name", to: "categories#index"
    get "/search-results-page", to: "categories#search_result_page", as: :search_result_page

    resources :categories, only: [:index]

    resources :promo_codes, only: [] do
      collection do
        get 'check_code'
      end
    end

    resources :transactions, only: [:show, :new, :create] do
      resources :transaction_addresses, only: [:create, :update]
      resources :shippers, only: [:create, :update]
      resources :helping_requests, only: [:create]
      member do
        get 'order_details'
      end
    end

    resources :transaction_addresses, only: [:new, :edit, :destroy] do
      member do
        put 'set_default_address'
      end
    end

    resources :transaction_addresses, only: [:create, :update]

    resources :carts, only: [] do
      collection do
        get 'get_shipping_rates_for_listing_items'
      end
    end

    namespace :admin do
      resource :custom_style, only: [:edit ,:create, :update]
      resource :support_info, only: [:edit ,:create, :update]
      resource :shipping_additional_fee, only: [:edit ,:create, :update]
      resources :promo_codes do
        collection do
          get :generate_code
        end
      end

      get '' => "getting_started_guide#index"

      resources :payment_preferences, only: [:index], param: :payment_gateway do
        collection do
          put :common_update
          put :update_stripe_keys
        end
        member do
          get :disable
          get :enable
        end
      end

      resource :checkout_setting, only: [:show, :update]
      get  "/paypal_preferences" => redirect("/%{locale}/admin/payment_preferences")
      get  "/paypal_preferences/account_create"       => "paypal_preferences#account_create"
      get  "/paypal_preferences/permissions_verified" => "paypal_preferences#permissions_verified"

      resource :setting, path: 'settings', only: [:show, :update]

      get "getting_started_guide"                        => "getting_started_guide#index",                  as: :getting_started_guide
      get "getting_started_guide/slogan_and_description" => "getting_started_guide#slogan_and_description", as: :getting_started_guide_slogan_and_description
      get "getting_started_guide/cover_photo"            => "getting_started_guide#cover_photo",            as: :getting_started_guide_cover_photo
      get "getting_started_guide/filter"                 => "getting_started_guide#filter",                 as: :getting_started_guide_filter

app/models/transaction/concerns/export_transaction.rb
module ExportTransaction
  extend ActiveSupport::Concern

  def last_activity
    [last_transition_at, conversation&.last_message_at].compact.max
  end

  included do
    class << self
      def for_community_sorted_by_column(community_id, sort_column, sort_direction, limit, offset)
        sort_column = "transactions.#{sort_column}" if sort_column.index('.').nil?
        exist.by_community(community_id)
          .with_payment_conversation
          .includes(:listing)
          .limit(limit)
          .offset(offset)
          .order("#{sort_column} #{sort_direction}")
      end

      def for_community_sorted_by_activity(community_id, sort_direction, limit, offset, eager_includes = false)
        tx_scope = exist.by_community(community_id)
          .with_payment_conversation_latest(sort_direction)
          .limit(limit)
          .offset(offset)
        tx_scope = tx_scope.for_csv_export if eager_includes
        tx_scope
      end
    end
  end
end

app/views/transactions/shipment_process/_shipment_bar.haml
.shipment-bar
  .contact-info.flex-items
    .item-1
      %span= t('transactions.label.contact')
    .item-2
      - if @transaction.starter
        %span= @transaction.starter.get_email
      - else
        %span= @shipping_address.email
    .item-3
      = link_to t('transactions.label.change'), checkout_transaction_path(@transaction.uuid_object)
  .shipping-address.flex-items
    .item-1
      %span= t('transactions.label.ship_to')
    .item-2
      %span= @shipping_address.full_address
    .item-3
      = link_to t('transactions.label.change'), checkout_transaction_path(@transaction.uuid_object)
  - if show_methos_row
    .shipping-method.flex-items
      .item-1
        %span Method
      .item-2
        %span= @transaction.shipping_method_label
      .item-3
      - unless @transaction.draft_order?
        = link_to t('transactions.label.change'), shipment_transaction_path(@transaction.uuid_object)

app/views/transactions/shipment_process/_shipment_methods.haml
.common-box
  .row
    .col-9
      .header-title
        %h2= t('transactions.label.shipping_method')
      .alert-warning{class: @transaction.will_pickup_on_friday? ? '' : 'hidden'}
        Your Equipment will be ready for Pick up on Friday. Please note we are closed on the Weekend.
  = form_for [@transaction, @transaction.shipper] do |form|
    .row
      .col-9
        .shipping-select-box{'data-uuid': @transaction.uuid_object }
          .items.enabled-shipping-select
            .radio-btn.center-items
              = form.radio_button :service_type, 'free'
            .shipping-service
              %span= t('transactions.label.pick_up')
            .price
              %strong= t('transactions.label.free')
          - @shipping_selection.each_with_index do |shipment, index|
            .items{class: @transaction.disabled_select_shipping? ? 'disabled-shipping-select': 'enabled-shipping-select'}
              .radio-btn.center-items
                = form.radio_button :service_type, shipment['service_type'], disabled: @transaction.disabled_select_shipping?
              .shipping-service
                %span= shipment["service_name"]
                .days-shippment
                  %span= shipping_type_to_humanized(shipment["service_type"])
              .price
                %strong= "#{shipment["total_charge"]['amount']} #{shipment["total_charge"]['currency']}"
    .row
      .col-9.center-items
        = form.submit t('transactions.btn_label.continue_to_payment'), class: "btn btn-submit"
      .col-9.center-items.back-to-cart
        = fa_icon "angle-left"
        = link_to t('transactions.btn_label.return_to_cart'), cart_path
    .row
      .col-9.br-top.copy-right
        %span= t('common.copy_right')

app/views/transactions/shipment_process/_shipment_promo_code.haml
.common-box.margin-0
  .shipping-promo-code{'data-uuid': @transaction.uuid_object}
    %span.fz-18= t('transactions.label.promo_code')
    .group.flex-items
      .input-promo-code
        = text_field_tag :promo_code, @promo_code
      .btn-promo-code
        = button_tag 'Apply', :class => "common-btn margin-0"
    %span.promo-code-error.alert-error.d-none
    .coupon-code-apply.hidden.padding-b-t-15
      %i.fa.fa-tag
      %span Coupon code applied