config/routes.rb
Rails.application.routes.draw do

  mount Delayed::Web::Engine, at: '/jobs'
  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get "/robots.txt" => RobotsGenerator

  get "/sitemap.xml.gz"                        => "sitemap#sitemap", format: :xml
  get "/sitemap/:sitemap_host/generate.xml.gz" => "sitemap#generate", format: :xml, :constraints => { sitemap_host: /[.\-\w]+/ }

  get "/:dv_file" => "domain_validation#index", constraints: {dv_file: /.*\.txt/}

  get "/design" => "design#design"

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  post '/webhooks/paypal_ipn' => 'paypal_ipn#ipn_hook', as: :paypal_ipn_hook
  post '/webhooks/plans' => 'plans#create'
  get '/webhooks/trials' => 'plans#get_trials'

  post '/bounces' => 'amazon_bounces#notification'

  get "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  get "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  get "/change_locale" => "i18n#change_locale", :as => :change_locale

  post '/after_ship/webhook' => 'after_ships#webhook'

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    resources :listings, only: [], defaults: { format: :json } do
      member do
        post :update_working_time_slots
      end
    end
  end

  match '/harmony_proxy/*harmony_path' => 'harmony_proxy#proxy', via: :all

  get "/ui_api/topbar_props" => "topbar_api#props"

  get '/_lp_preview' => 'landing_page#preview', as: :landing_page_preview

  locale_regex_string = Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(Sharetribe::REMOVED_LOCALES.to_a).join("|")
  locale_matcher = Regexp.new(locale_regex_string)
  locale_matcher_anchored = Regexp.new("^(#{locale_regex_string})$")

  get '/:locale/' => 'landing_page#index', as: :landing_page_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/' => 'landing_page#index', as: :landing_page_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  get '/:locale/s' => 'homepage#index', as: :search_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/s' => 'homepage#index', as: :search_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  post '/search_listing' => 'homepage#auto_complete_search', as: :auto_complete_search
  get '/search_listing_by_name' => 'listings#search_by_name', as: :search_by_name
  post '/add_packing_dimension' => 'listings#add_packing_dimension', as: :add_packing_dimension

  get '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  get '/' => 'homepage#index', as: :homepage_without_locale
  get '/:locale/s', to: redirect('/%{locale}', status: 307), constraints: { locale: locale_matcher }
  get '/s', to: redirect('/', status: 307)

  get '/500' => 'errors#server_error'
  get '/404' => 'errors#not_found', :as => :error_not_found
  get '/406' => 'errors#not_acceptable', :as => :error_not_acceptable
  get '/410' => 'errors#gone', as: :error_gone
  get '/community_not_found' => 'errors#community_not_found', as: :community_not_found
  get '/not_available' => 'application#not_available', as: :community_not_available

  get '/load_cart', to: 'listings#load_cart'

  resources :communities, only: [:new, :create]

  devise_for :people, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "omniauth" }

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do
    get '/cart', to: 'listings#cart'

    put '/mercury_update' => "mercury_update#update", :as => :mercury_update

    get "/transactions/op_status/:process_token" => "paypal_service/checkout_orders#paypal_op_status", as: :paypal_op_status
    get "/transactions/transaction_op_status/:process_token" => "transactions#transaction_op_status", :as => :transaction_op_status
    get "/transactions/created/:transaction_id" => "transactions#created", as: :transaction_created
    get "/transactions/finalize_processed/:process_token" => "transactions#finalize_processed", as: :transaction_finalize_processed

    get "/transactions/new" => "transactions#new", as: :new_transaction
    get "/transactions/:uuid/checkout" => "transactions#checkout", as: :checkout_transaction
    get "/transactions/:uuid/shipment" => "transactions#shipment", as: :shipment_transaction
    get "/transactions/:uuid/change_shipping_selection" => "transactions#change_shipping_selection", as: :change_shipping_selection_transaction
    get "/transactions/:uuid/update_promo_code" => "transactions#update_promo_code", as: :update_promo_code_transaction
    get "/transactions/:uuid/change_state_shipping_form" => "transactions#change_state_shipping_form", as: :change_state_shipping_form
    get "/transactions/:uuid/payment" => "transactions#payment", as: :payment_transaction
    get "/transactions/:uuid/thank_you" => "transactions#thank_you", as: :thank_you_transaction
    post "/transactions/:transaction_id/pay_order" => "transaction_addresses#pay_order", as: :pay_order_transaction

    get "/listings/:listing_id/book", :to => redirect { |params, request|
      "/#{params[:locale]}/listings/#{params[:listing_id]}/initiate?#{request.query_string}"
    }
    post "/listings/:listing_id/booked"    => "preauthorize_transactions#initiated", as: :booked # POST request, no redirect

    get "/listings/:listing_id/initiate"   => "preauthorize_transactions#initiate", :as => :initiate_order
    post "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    post "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    get "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    get "/logout" => "sessions#destroy", :as => :logout
    get "/confirmation_pending" => "community_memberships#confirmation_pending", :as => :confirmation_pending
    get "/login" => "sessions#new", :as => :login
    get "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    get "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    get '/:person_id/settings/payments' => 'payment_settings#index', :as => :person_payment_settings
    post '/:person_id/settings/payments' => 'payment_settings#create', :as => :create_person_payment_settings
    put '/:person_id/settings/payments' => 'payment_settings#update', :as => :update_person_payment_settings
    get '/:person_id/settings/payments/paypal_account' => 'paypal_accounts#index', :as => :paypal_account_settings_payment

    get  '/community_memberships/pending_consent' => 'community_memberships#pending_consent', as: :pending_consent
    post '/community_memberships/give_consent'    => 'community_memberships#give_consent', as: :give_consent
    get  '/community_memberships/access_denied'   => 'community_memberships#access_denied', as: :access_denied

    get  '/community_memberships/check_email_availability_and_validity' => 'community_memberships#check_email_availability_and_validity'
    get  '/community_memberships/check_invitation_code'                 => 'community_memberships#check_invitation_code'

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    get "/categories", :to => redirect { |params, request|
      "/#{params[:locale]}/rent/#{request[:category]}/#{request[:subcategories]}/#{request[:children_categories]}"
    }

    get "rent/:category_name/:subcategory_name", to: "categories#index"
    get "rent/:category_name/:subcategory_name/:childcategory_name", to: "categories#index"
    get "/search-results-page", to: "categories#search_result_page", as: :search_result_page

    resources :categories, only: [:index]

    resources :promo_codes, only: [] do
      collection do
        get 'check_code'
      end
    end

    resources :transactions, only: [:show, :new, :create] do
      resources :transaction_addresses, only: [:create, :update]
      resources :shippers, only: [:create, :update]
      resources :helping_requests, only: [:create]
      member do
        get 'order_details'
      end
    end

    resources :transaction_addresses, only: [:new, :edit, :destroy] do
      member do
        put 'set_default_address'
      end
    end

    resources :transaction_addresses, only: [:create, :update]

    resources :carts, only: [] do
      collection do
        get 'get_shipping_rates_for_listing_items'
      end
    end

    namespace :admin do
      resource :custom_style, only: [:edit ,:create, :update]
      resource :support_info, only: [:edit ,:create, :update]
      resource :shipping_additional_fee, only: [:edit ,:create, :update]
      resources :promo_codes do
        collection do
          get :generate_code
        end
      end

      get '' => "getting_started_guide#index"

      resources :payment_preferences, only: [:index], param: :payment_gateway do
        collection do
          put :common_update
          put :update_stripe_keys
        end
        member do
          get :disable
          get :enable
        end
      end

      resource :checkout_setting, only: [:show, :update]
      get  "/paypal_preferences" => redirect("/%{locale}/admin/payment_preferences")

app/controllers/admin/community_draft_orders_controller.rb
class Admin::CommunityDraftOrdersController < Admin::AdminBaseController
  before_action :set_selected_left_navi_link
  before_action :set_service, only: :index
  before_action :set_order, only: [:edit, :update]

  def index
    @draft_orders = Transaction.all.draft_order.abandoned_order.order(id: :desc)
    @draft_orders = @draft_orders.paginate(page: params[:page])
  end

  def new
    @transaction = Transaction.new
  end

  def edit
    person = @transaction.starter
    shipping_address =  @transaction.shipping_address
    billing_address = @transaction.billing_address
    @person_information = {
      person: person,
      shipping_address: shipping_address,
      billing_address: billing_address,
      transaction: @transaction
    }
  end

  def update
    if @transaction.update_attributes(transaction_params)
      redirect_to action: 'edit', id: @transaction.id
    end
  end

  private

  def set_selected_left_navi_link
    @selected_left_navi_link = "draft_orders"
  end

  def set_service
    @service = Admin::DraftOrdersService.new(
      community: @current_community,
      params: params)
  end

  def set_order
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:current_state, :canceled_order_note)
  end
end

app/views/admin/community_draft_orders/_edit_customer_note.haml
.modal#edit-customer-note
  = form_for order, url: {controller: "admin/community_draft_orders", action: :update} do |form|    
    .row.title.margin-bt-0
      = "Edit Customer Note"
    .row
      %span= "Order Note"
      = form.text_field :note, {placeholder: "Order note."}
    .row.footer
      = form.submit "Save", class: "button right margin-l-5"
      %a.button.right{rel: "modal:close"}= "Cancel"

app/views/admin/community_draft_orders/_listings.haml
%table.margin-bt-15
  %thead
    %tr
      %th
      %th
      %th
        = "Price per item"
      %th
      %th
        = "Quantity"
      %th
      %th
  %tbody
  - transaction.transaction_items.each do |item|
    - listing = item.listing
    - if listing
      %tr{'data-id': item.id}
        %td.w-5.padding-0
          = hidden_field_tag "id", listing.id, class: "ids"
          = image_tag listing.main_image, alt: @current_community.image_alt_text
        %td.w-45.padding-0
          = listing.title
        %td
          = text_field_tag 'price', to_CAD(item.price_cents), class: 'craft-order-price'
        %td
          = "x"
        %td
          = text_field_tag 'quantity', item.quantity, class: 'craft-order-quantity'
        %td.total-price
          = money_to_humanized(item.price_cents * item.quantity)
        %td
          %i.icon-times.remove-draft-listing-item
    - else
      %p No listing available
  - transaction.custom_items.is_listing.each do |item|
    %tr{'data-id': item.id}
      %td.w-5.padding-0
        = hidden_field_tag "id", item.id, class: "ids"
      %td.w-45.padding-0
        = item.name
      %td
        = text_field_tag 'price', item.price_cents/100, class: 'draft-custom-item-price'
      %td
        = "x"
      %td
        = text_field_tag 'quantity', item.quantity, class: 'draft-custom-item-quantity'
      %td.total-price
        = money_to_humanized(item.price_cents * item.quantity)
      %td
        %i.icon-times.remove-draft-custom-item

app/views/admin/community_draft_orders/_order.haml
%tr
  %td
    %a{href: edit_admin_community_draft_order_path(@current_community, order)}= "#D#{order.id}"
  %td
    = order.created_at.to_formatted_s(:long)
  %td
    = order.starter ? order.starter.given_name : "-"
  %td
    - if order.completed?
      .state-label.paid-state-label
        %i.fa.fa-usd
        %span Paid
    - else
      .state-label.unpaid-state-label
        %i.fa.fa-circle
        %span Unpaid
  %td
    = money_to_humanized((TransactionMoneyCalculation.new(order, session, @current_user).get_final_price_for_draft_order))

app/views/admin/community_draft_orders/_table.haml
%table#admin-draft-orders
  %thead
    %tr
      %th
        = render partial: "layouts/sort_link", locals: { column: "draft", direction: sort_link_direction("draft"), title: t("admin.communities.manage_draft_orders.draft")}
      %th
        = render partial: "layouts/sort_link", locals: { column: "date", direction: sort_link_direction("date"), title: t("admin.communities.manage_draft_orders.date")}
      %th
        = t("admin.communities.manage_draft_orders.customer")
      %th
        = render partial: "layouts/sort_link", locals: { column: "date", direction: sort_link_direction("date"), title: t("admin.communities.manage_draft_orders.status")}
      %th
        = render partial: "layouts/sort_link", locals: { column: "date", direction: sort_link_direction("date"), title: t("admin.communities.manage_draft_orders.total")}
  %tbody
    - @draft_orders.each do |order|
      = render 'order', order: order

.row
  .col-12
    = will_paginate @draft_orders

app/views/admin/community_draft_orders/edit.haml
= javascript_include_tag "#{STRIPE_JS_HOST}/v3/"
= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section#create-draft-order
  .row
    .col-12
      %h2.margin-bt-0 Create order
  = form_for [:admin, @transaction], url: update_draft_order_admin_community_transaction_path(@current_community, @transaction), method: :post do |f|
    .row
      #draft_order_id{'data-id': @transaction.id}
      = hidden_field_tag :draft_order_person_id
      .col-12
        .row
          .col-9.order-details
            .col-12
              %h3.left= "Order details"
              %a.right{href: "#custom-item-modal", rel: "modal:open"}= "Add custom item"
            .col-12
              .row.search-product
                = text_field_tag :product_name, params[:product_name], placeholder: 'Search products'
                %a.button#browse-products{href: "#browse-product-modal", rel: "modal:open"}= "Browse products"
              #craft-order-product-list
              .row.payment-info#draft-payment-info
                = render partial: 'admin/community_transactions/payment_info', locals: {transaction: @transaction}
            .col-12.email-invoice
              .col-6
                %i.icon-file-text-alt.left
                %span.left= "EMAIL INVOICE"
              .col-6
                %a.button.right#send-invoice-email{href: "#send-invoice-email-modal", rel: "modal:open"}= "Email Invoice"
            .col-12
              .paid-type
                %a.button.right{href: "#payment-with-credit-card-modal", rel: "modal:open"}= "Pay with credit card"
                = f.button 'Mark as pending', name: "draft_order_status", value: "pending", class: 'button right'
                = f.button 'Mark as paid', name: "draft_order_status", value: "paid", class: 'button right'
                %p.right= "ACCEPT PAYMENT"
                %i.icon-money.right
          .col-3.find-create-customer
            .find-customer
              .row
                %h3= "Find or create a customer"
              = text_field_tag :customer_name, params[:customer_name], placeholder: 'Search products'
            .customer-info.margin-t-15
              - if @transaction.starter
                = render partial: 'admin/person_custom_fields/person_information', locals: {person_information: @person_information}
      .row
        .col-12
          = f.submit 'Save Draft Order', class: 'button right'

= render 'admin/community_transactions/browse_product_modal', listings: @current_community.listings
= render 'admin/community_transactions/add_custom_item_modal'
= render 'admin/community_transactions/create_new_customer_modal'
= render 'admin/community_transactions/send_invoice_email_modal'
= render 'admin/community_transactions/review_email'
= render 'admin/community_transactions/payment_with_credit_card'

- content_for :extra_javascript do
  :javascript
    window.ST.StripePayment.initIntent({
      publishable_key: '#{APP_CONFIG.stripe_api_publishable_key}'
    });
    Shipment.run();

app/views/admin/community_draft_orders/index.haml
= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section#manage-draft-orders
  .row
    .col-6
      %h2= t("admin.communities.manage_draft_orders.draft_orders")
    .col-6
      = link_to 'Create Order', new_admin_community_transaction_path(@current_community), class: "button create-order-button"
  .row
    .col-12
      = text_field_tag :q, params[:q], placeholder: t('admin.communities.manage_draft_orders.search_by_customer_name')
  .row
    .col-12
      = render "table"