config/routes.rb
  post '/bounces' => 'amazon_bounces#notification'

  get "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  get "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  get "/change_locale" => "i18n#change_locale", :as => :change_locale

  post '/after_ship/webhook' => 'after_ships#webhook'

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    resources :listings, only: [], defaults: { format: :json } do
      member do
        post :update_working_time_slots
      end
    end
  end

  match '/harmony_proxy/*harmony_path' => 'harmony_proxy#proxy', via: :all

  get "/ui_api/topbar_props" => "topbar_api#props"

  get '/_lp_preview' => 'landing_page#preview', as: :landing_page_preview

  locale_regex_string = Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(Sharetribe::REMOVED_LOCALES.to_a).join("|")
  locale_matcher = Regexp.new(locale_regex_string)
  locale_matcher_anchored = Regexp.new("^(#{locale_regex_string})$")

  get '/:locale/' => 'landing_page#index', as: :landing_page_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/' => 'landing_page#index', as: :landing_page_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  get '/:locale/s' => 'homepage#index', as: :search_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/s' => 'homepage#index', as: :search_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  post '/search_listing' => 'homepage#auto_complete_search', as: :auto_complete_search
  get '/search_listing_by_name' => 'listings#search_by_name', as: :search_by_name
  post '/add_packing_dimension' => 'listings#add_packing_dimension', as: :add_packing_dimension

  get '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  get '/' => 'homepage#index', as: :homepage_without_locale
  get '/:locale/s', to: redirect('/%{locale}', status: 307), constraints: { locale: locale_matcher }
  get '/s', to: redirect('/', status: 307)

  get '/500' => 'errors#server_error'
  get '/404' => 'errors#not_found', :as => :error_not_found
  get '/406' => 'errors#not_acceptable', :as => :error_not_acceptable
  get '/410' => 'errors#gone', as: :error_gone
  get '/community_not_found' => 'errors#community_not_found', as: :community_not_found
  get '/not_available' => 'application#not_available', as: :community_not_available

  get '/load_cart', to: 'listings#load_cart'

  resources :communities, only: [:new, :create]

  devise_for :people, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "omniauth" }

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do
    get '/cart', to: 'listings#cart'

    put '/mercury_update' => "mercury_update#update", :as => :mercury_update

    get "/transactions/op_status/:process_token" => "paypal_service/checkout_orders#paypal_op_status", as: :paypal_op_status
    get "/transactions/transaction_op_status/:process_token" => "transactions#transaction_op_status", :as => :transaction_op_status
    get "/transactions/created/:transaction_id" => "transactions#created", as: :transaction_created
    get "/transactions/finalize_processed/:process_token" => "transactions#finalize_processed", as: :transaction_finalize_processed

    get "/transactions/new" => "transactions#new", as: :new_transaction
    get "/transactions/:uuid/checkout" => "transactions#checkout", as: :checkout_transaction
    get "/transactions/:uuid/shipment" => "transactions#shipment", as: :shipment_transaction
    get "/transactions/:uuid/change_shipping_selection" => "transactions#change_shipping_selection", as: :change_shipping_selection_transaction
    get "/transactions/:uuid/update_promo_code" => "transactions#update_promo_code", as: :update_promo_code_transaction
    get "/transactions/:uuid/change_state_shipping_form" => "transactions#change_state_shipping_form", as: :change_state_shipping_form
    get "/transactions/:uuid/payment" => "transactions#payment", as: :payment_transaction
    get "/transactions/:uuid/thank_you" => "transactions#thank_you", as: :thank_you_transaction
    post "/transactions/:transaction_id/pay_order" => "transaction_addresses#pay_order", as: :pay_order_transaction

    get "/listings/:listing_id/book", :to => redirect { |params, request|
      "/#{params[:locale]}/listings/#{params[:listing_id]}/initiate?#{request.query_string}"
    }
    post "/listings/:listing_id/booked"    => "preauthorize_transactions#initiated", as: :booked # POST request, no redirect

    get "/listings/:listing_id/initiate"   => "preauthorize_transactions#initiate", :as => :initiate_order
    post "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    post "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    get "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    get "/logout" => "sessions#destroy", :as => :logout
    get "/confirmation_pending" => "community_memberships#confirmation_pending", :as => :confirmation_pending
    get "/login" => "sessions#new", :as => :login
    get "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    get "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    get '/:person_id/settings/payments' => 'payment_settings#index', :as => :person_payment_settings
    post '/:person_id/settings/payments' => 'payment_settings#create', :as => :create_person_payment_settings
    put '/:person_id/settings/payments' => 'payment_settings#update', :as => :update_person_payment_settings
    get '/:person_id/settings/payments/paypal_account' => 'paypal_accounts#index', :as => :paypal_account_settings_payment

    get  '/community_memberships/pending_consent' => 'community_memberships#pending_consent', as: :pending_consent
    post '/community_memberships/give_consent'    => 'community_memberships#give_consent', as: :give_consent
    get  '/community_memberships/access_denied'   => 'community_memberships#access_denied', as: :access_denied

    get  '/community_memberships/check_email_availability_and_validity' => 'community_memberships#check_email_availability_and_validity'
    get  '/community_memberships/check_invitation_code'                 => 'community_memberships#check_invitation_code'

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    get "/categories", :to => redirect { |params, request|
      "/#{params[:locale]}/rent/#{request[:category]}/#{request[:subcategories]}/#{request[:children_categories]}"
    }

    get "rent/:category_name/:subcategory_name", to: "categories#index"
    get "rent/:category_name/:subcategory_name/:childcategory_name", to: "categories#index"
    get "/search-results-page", to: "categories#search_result_page", as: :search_result_page

    resources :categories, only: [:index]

    resources :promo_codes, only: [] do
      collection do
        get 'check_code'
      end
    end

    resources :transactions, only: [:show, :new, :create] do
      resources :transaction_addresses, only: [:create, :update]
      resources :shippers, only: [:create, :update]
      resources :helping_requests, only: [:create]
      member do
        get 'order_details'
      end
    end

    resources :transaction_addresses, only: [:new, :edit, :destroy] do
      member do
        put 'set_default_address'
      end
    end

    resources :transaction_addresses, only: [:create, :update]

    resources :carts, only: [] do
      collection do
        get 'get_shipping_rates_for_listing_items'
      end
    end

    namespace :admin do
      resource :custom_style, only: [:edit ,:create, :update]
      resource :support_info, only: [:edit ,:create, :update]
      resource :shipping_additional_fee, only: [:edit ,:create, :update]
      resources :promo_codes do
        collection do
          get :generate_code
        end
      end

      get '' => "getting_started_guide#index"

      resources :payment_preferences, only: [:index], param: :payment_gateway do
        collection do
          put :common_update
          put :update_stripe_keys
        end
        member do
          get :disable
          get :enable
        end
      end

      resource :checkout_setting, only: [:show, :update]
      get  "/paypal_preferences" => redirect("/%{locale}/admin/payment_preferences")
      get  "/paypal_preferences/account_create"       => "paypal_preferences#account_create"
      get  "/paypal_preferences/permissions_verified" => "paypal_preferences#permissions_verified"

      resource :setting, path: 'settings', only: [:show, :update]

      get "getting_started_guide"                        => "getting_started_guide#index",                  as: :getting_started_guide
      get "getting_started_guide/slogan_and_description" => "getting_started_guide#slogan_and_description", as: :getting_started_guide_slogan_and_description
      get "getting_started_guide/cover_photo"            => "getting_started_guide#cover_photo",            as: :getting_started_guide_cover_photo
      get "getting_started_guide/filter"                 => "getting_started_guide#filter",                 as: :getting_started_guide_filter

app/models/transaction/concerns/export_transaction.rb
module ExportTransaction
  extend ActiveSupport::Concern

  def last_activity
    [last_transition_at, conversation&.last_message_at].compact.max
  end

  included do
    class << self
      def for_community_sorted_by_column(community_id, sort_column, sort_direction, limit, offset)
        sort_column = "transactions.#{sort_column}" if sort_column.index('.').nil?
        exist.by_community(community_id)
          .with_payment_conversation
          .includes(:listing)
          .limit(limit)
          .offset(offset)
          .order("#{sort_column} #{sort_direction}")
      end

      def for_community_sorted_by_activity(community_id, sort_direction, limit, offset, eager_includes = false)
        tx_scope = exist.by_community(community_id)
          .with_payment_conversation_latest(sort_direction)
          .limit(limit)
          .offset(offset)
        tx_scope = tx_scope.for_csv_export if eager_includes
        tx_scope
      end
    end
  end
end

app/views/transactions/_details.haml
.message-avatar-padding
  .row
    .col-12

      %h2
        = link_to_unless @transaction.listing.deleted, @transaction.listing.title, listing_path(id: @transaction.listing.id)

      - if price_break_down_locals.present?
        = render partial: "transactions/price_break_down", locals: price_break_down_locals.merge(is_author: is_author)

      = render partial: "transactions/shipping_address", locals: { shipping_address: @transaction.shipping_address }

      %div{:id => "transaction_status"}
        = render :partial => "transactions/status/status", :locals => { :__transaction_model => @transaction, role: role, is_author: is_author }

app/views/transactions/_price_break_down.haml
- has_buyer_fee = buyer_fee.present? && buyer_fee > 0
.initiate-transaction-totals
  - if booking
    .initiate-transaction-per-unit-wrapper
      %span.initiate-transaction-per-unit-label
        - if unit_type == :day
          = t("transactions.initiate.price_per_day")
        - elsif unit_type == :night
          = t("transactions.initiate.price_per_night")
        - elsif unit_type == :hour
          = t("transactions.initiate.price_per_hour")
        - else
          = t("transactions.initiate.price_per_unit")
      %span.initiate-transaction-per-unit-value
        = MoneyViewUtils.to_humanized(listing_price)

    .initiate-transaction-booking-wrapper
      - if per_hour
        %span.initiate-transaction-booking-label
          = t('transactions.initiate.booked_hours_label', count: duration)
        %span.initiate-transaction-booking-value
          = l start_time.to_date, format: :long_with_abbr_day_name
          = '-'
          = t("transactions.initiate.start_end_time",
            start_time: l(start_time, format: :hours_only),
            end_time: l(end_time, format: :hours_only))
          = t("transactions.initiate.duration_in_hours", count: duration)
      - else
        %span.initiate-transaction-booking-label
          - if unit_type == :day
            = use_new_translation("transactions.initiate.booked_days_label", count: duration).or_fallback_to("transactions.initiate.booked_days")
          - else
            = use_new_translation("transactions.initiate.booked_nights_label", count: duration).or_fallback_to("transactions.initiate.booked_nights")
        %span.initiate-transaction-booking-value
          = l start_on, format: :long_with_abbr_day_name
          = "-"
          - if unit_type == :day
            = l (end_on - 1.day), format: :long_with_abbr_day_name
            = "(#{pluralize(duration, t("listing_conversations.preauthorize.day"), t("listing_conversations.preauthorize.days"))})"
          - else
            = l end_on, format: :long_with_abbr_day_name
            = "(#{pluralize(duration, t("listing_conversations.preauthorize.night"), t("listing_conversations.preauthorize.nights"))})"

  - elsif quantity.present? && localized_unit_type.present?
    .initiate-transaction-per-unit-wrapper
      %span.initiate-transaction-per-unit-label
        = t("transactions.price_per_quantity", unit_type: localized_unit_type)
      %span.initiate-transaction-per-unit-value
        = MoneyViewUtils.to_humanized(listing_price)
    - if quantity > 1
      .initiate-transaction-quantity-wrapper
        %span.initiate-transaction-quantity-label
          = localized_selector_label || t("transactions.initiate.quantity")
        %span.initiate-transaction-quantity-value
          = quantity

  - if subtotal.present?
    .initiate-transaction-sum-wrapper#tx-subtotal
      %span.initiate-transaction-sum-label
        = t("transactions.initiate.subtotal")
      %span.initiate-transaction-sum-value
        = MoneyViewUtils.to_humanized(subtotal)

  - if shipping_price.present?
    .initiate-transaction-shipping-price-wrapper
      %span.initiate-transaction-shipping-price-label
        = t("transactions.initiate.shipping-price")
      %span.initiate-transaction-shipping-price-value
        = MoneyViewUtils.to_humanized(shipping_price)

  - if is_author
    - unless has_buyer_fee
      .initiate-transaction-sum-wrapper#tx-total-to-pay
        %span.initiate-transaction-sum-label
          = t("transactions.total_to_pay")
        %span.initiate-transaction-sum-value
          = MoneyViewUtils.to_humanized(total)

    - if fee.present? && fee > 0
      .initiate-transaction-sum-wrapper#tx-fee
        %span.initiate-transaction-sum-label
          = t("conversations.accept.service_fee_label")
        %span.initiate-transaction-sum-value
          = "-#{MoneyViewUtils.to_humanized(fee)}"

  - if has_buyer_fee && !is_author
    .initiate-transaction-sum-wrapper#tx-buyer-fee
      %span.initiate-transaction-sum-label
        = t("conversations.accept.buyer_service_fee_label")
      %span.initiate-transaction-sum-value
        = "#{is_author ? '-' : ''}#{MoneyViewUtils.to_humanized(buyer_fee)}"

  - if total.present?
    .initiate-transaction-total-wrapper
      %span.initiate-transaction-total-label
        - if total_label.present?
          = total_label
        - else
          = t("transactions.total")
      %span.initiate-transaction-total-value
        = MoneyViewUtils.to_humanized(is_author ? seller_gets : total)

app/views/transactions/_process_bar.haml
.row.process-bar
  .col-12
    = link_to "Cart", cart_path, class: "#{current_page == 'cart' ? 'active-el' : ''}"
    >
    = link_to "Shipping", shipment_transaction_path(transaction.uuid_object), class: "#{current_page == 'shipment' ? 'active-el' : ''}"
    >
    = link_to "Payment", payment_transaction_path(transaction.uuid_object), class: "#{current_page == 'payment' ? 'active-el' : ''}"

app/views/transactions/_shipping_address.haml
- fields = [:name, :phone, :street1, :street2, :postal_code, :city, :state_or_province, :country]
- if shipping_address && shipping_address.slice(*fields).values.any?
  - shipping_address[:country] ||= CountryI18nHelper.translate_country(shipping_address[:country_code])
  .shipping-address-container
    %h2= t("shipping_address.shipping_address")
    - fields.map do |field|
      - if shipping_address[field].present?
        - if shipping_address[field] == :name
          .shipping-address-name= shipping_address[field]
        - else
          .shipping-address-row= shipping_address[field]

app/views/transactions/change_shipping_selection.js.erb
//desktop-display
$(".checkout-section .order-summary-box").html("<%= j render(partial: 'transactions/checkout_process/order_summary', locals: { transaction: @transaction, state: @state, default_shipping_fee: @default_shipping_fee }) %>");
//mobile-display
<% if @transaction.will_pickup_on_friday? %>
  $('.alert-warning').slideDown("slow");
<% else %>
  $('.alert-warning').slideUp("slow");
<% end %>

app/views/transactions/change_state_shipping_form.js.erb
// desktop-display
$(".checkout-section .order-summary-box").html("<%= j render(partial: 'transactions/checkout_process/order_summary', locals: { transaction: @transaction, state: @state, default_shipping_fee: @default_shipping_fee }) %>");
// mobile-display
$(".checkout-section .mobile-order-summary-box").html("<%= j render(partial: 'transactions/checkout_process/mobile_design/order_summary', locals: { transaction: @transaction, state: @state, default_shipping_fee: @default_shipping_fee }) %>");

app/views/transactions/checkout.haml
.brown-background
  .checkout-section
    .wrapper
      .desktop-display
        .row
          .col-12
            .header-checkout= t('transactions.label.checkout')
        .row
          .col-8.margin-bt-50
            = render partial: "transactions/checkout_process/rent_date_bar"
        .row
          .col-8
            = render partial: "transactions/checkout_process/contact_info"
          .col-4.order-summary-box
            = render partial: "transactions/checkout_process/order_summary", locals: {transaction: @transaction, state: DEFAULT_STATE, default_shipping_fee: @default_shipping_fee}
      .mobile-display
        .row
          .col-12
            .header-checkout.padding-0= t('transactions.label.checkout')
        .row
          .col-12
            = render partial: "transactions/checkout_process/rent_date_bar"
        .row
          .col-12.mobile-order-summary-box
            = render partial: "transactions/checkout_process/mobile_design/order_summary", locals: {transaction: @transaction, state: DEFAULT_STATE, default_shipping_fee: @default_shipping_fee}
          - unless @current_user
            .col-12.padding-0.fz-14.text-r
              %span= t('common.account_question')
              = link_to t('common.log_in'), login_path
          .col-12.mobile-contact-info
            = render partial: "transactions/checkout_process/mobile_design/contact_info"

- content_for :javascript do
  ValidateForm.run();
  KlaviyoTracking.trackingStartedCheckout(#{raw @started_checkout_as_json.to_json})

app/views/transactions/draft_orders.js.erb
$('.product-list').html("<%= j render(partial: "/admin/community_draft_orders/_listings", listings: @listings) %>")

app/views/transactions/new.haml
-# - content_for :extra_javascript do
-#   :javascript
-#     ST.transaction.initializeFreeTransactionForm('#{I18n.locale}');

-# - content_for :title_header do
-#   %h1
-#     = action_button_label
-#     = link_to(listing[:title], listing_path(listing[:id]))

-# #new_message_form.centered-section

-#   - author_link = link_to(author[:display_name], person_path(username: author[:username]))

-#   .preauthorize-section
-#     %h2.preauthorize-details-title
-#       = t("listing_conversations.preauthorize.details")

-#     %ul.no-bullets
-#       %li
-#         %div
-#           = t("listing_conversations.preauthorize.by", listing: link_to("#{listing[:title]}", listing_path(listing[:id])), author: author_link).html_safe

-#       - m_price_break_down.each do |price_break_down|
-#         %li
-#           = render partial: "transactions/price_break_down", locals: price_break_down.merge(is_author: false)

-#   = form_tag(form_action, method: :post, id: "transaction-form") do

-#     = hidden_field_tag(:start_on, booking_start)
-#     = hidden_field_tag(:end_on, booking_end)


-#     .preauthorize-section
-#       %h2
-#         = t("conversations.new.send_message_to_user", person: author_link).html_safe
-#       .row
-#         .col-12
-#           = text_area_tag(:message, nil, :class => "text_area")

-#       - if quantity
-#         = hidden_field_tag(:quantity, quantity)

-#       .row
-#         .col-12
-#           = button_tag t("conversations.new.send_message"), :class => "send_button"

app/views/transactions/order_details.haml
.brown-background.padding-10
  .account-section
    .wrapper
      .row
        .col-12.flex-items.margin-b-t-10
          %span.fz-22 Order Details
      .desktop-display
        #order-details.margin-bt-20
          .row
            .col-3
              %span.block.fz-22= @transaction.created_at.to_date.to_formatted_s(:long)
              %p= t('transactions.order_details.order_number', number: @transaction.order_number)
              %span.block= t('transactions.order_details.total_quantity', quantity: @transaction.total_quantity).html_safe
              %span.block= t('transactions.order_details.arrival_date', date: @transaction.booking.start_on).html_safe
              %span.block= t('transactions.order_details.return_date', date: @transaction.booking.end_on).html_safe
              %span.block= t('transactions.order_details.rental_duration', number: @transaction.booking.duration).html_safe
            .col-3
              %p.bold Ship to
              %span.block= @transaction.shipping_address.fullname
              %span.block.uppercase= @transaction.shipping_address.apartment
              %span.block.uppercase= @transaction.shipping_address.get_street1
              %span.block.uppercase= "#{@transaction.shipping_address.get_city}, #{CANADA_PROVINCES.key(@transaction.shipping_address.get_state_or_province)} #{@transaction.shipping_address.get_postal_code}"
              %p.uppercase= @transaction.shipping_address.format_phone
              %span.block Payment Information
              %span= money_to_humanized(@transaction.stripe_payments.last.sum_cents)
            .col-3
              %p.bold Order Summary
              .flex-items
                .width-50
                  %span Subtotal:
                .width-50.align-right
                  %span= money_to_humanized(@transaction.payment.subtotal_cents)
              - if @transaction.promo_code
                .flex-items
                  .width-70
                    %span= "Promo Code (#{@transaction.promo_code.code})"
                  .width-30.align-right
                    %span= "- #{money_to_humanized(@calculate_money.get_discount_for_all_products_cart)}"
              .flex-items
                .width-50
                  %span= "Shipping (#{@transaction.shipper.service_delivery.upcase}):"
                .width-50.align-right
                  %span= "$#{@transaction.shipper.amount}"
              .flex-items.br-bottom
                .width-50
                  %span Sales Tax:
                .width-50.align-right
                  %span= money_to_humanized(@transaction.payment.fee_cents)
              / .flex-items.br-bottom
              /   .width-70
              /     %span Movri Coverage:
              /   .width-30.align-right
              /     %span= money_to_humanized(@transaction.coverage_cents)
              .flex-items
                .width-50
                  %span.bold Total
                .width-50.align-right
                  %span.bold= money_to_humanized(@transaction.stripe_payments.last.sum_cents)
            .col-3
              %span= "<strong>#{@transaction.total_quantity} products</strong> in this order".html_safe
              .btn-link
                - if @transaction.shipper.ups?
                  = link_to "Track Package", UPS_TRACKING_PACKAGE_WEB, target: :_blank
                - else
                  = link_to "Track Package", FEDEX_TRACKING_PACKAGE_WEB, target: :_blank
        .account-list-orders
          .white-background
            .row.margin-bt-20
              .col-12.padding-20
                .flex-items.data-header.padding-5.brown-background
                  .width-10
                  .width-40
                  .width-20.center-items
                    %span QTY
                  .width-30.center-items
                    %span Price
                  / .width-20.center-items
                  /   %span MOVRI COVERAGE
                - @transaction.transaction_items.each do |item|
                  - listing = item.listing
                  .account-listing-item.br-bottom
                    .flex-items.padding-5
                      .width-10.center-items
                        = image_tag listing.main_image, class: "width-100", alt: @current_community.image_alt_text
                      .width-40
                        %p.margin-0.title= link_to listing.title, listing_path(listing)
                        %p.margin-0.sku.uppercase= "SKU: #{listing.sku ? listing.sku : 'OLLC62F'}"
                      .width-20.center-items
                        %p= item.quantity
                      .width-30.center-items
                        = money_to_humanized(item.price_cents)
                      / .width-20.center-items
                      /   = money_to_humanized(item.coverage_price_cents)
      .mobile-display.fz-14
        #order-details.margin-bt-20
          .row
            .display-flex
              .width-50.padding-0
                %span.block.fz-22= @transaction.created_at.to_date.to_formatted_s(:long)
                %p= t('transactions.order_details.order_number', number: @transaction.order_number)
                %span= "Total Items: #{@transaction.total_quantity}"
                %span.block= t('transactions.order_details.arrival_date', date: @transaction.booking.start_on).html_safe
                %span.block= t('transactions.order_details.return_date', date: @transaction.booking.end_on).html_safe
                %span.block= t('transactions.order_details.rental_duration', number: @transaction.booking.duration).html_safe
              .width-50
                %p.bold Ship to
                %span.block= @transaction.shipping_address.fullname
                %span.block.uppercase= @transaction.shipping_address.apartment
                %span.block.uppercase= @transaction.shipping_address.get_street1
                %span.block.uppercase= "#{@transaction.shipping_address.get_city}, #{CANADA_PROVINCES.key(@transaction.shipping_address.get_state_or_province)} #{@transaction.shipping_address.get_postal_code}"
                %p.uppercase= @transaction.shipping_address.format_phone
                %span.block Payment Information
                %span= money_to_humanized(@transaction.stripe_payments.last.sum_cents)
          .row
            .width-70.padding-0
              %p.bold Order Summary
              .flex-items
                .width-50
                  %span Subtotal:
                .width-50.align-right
                  %span= money_to_humanized(@transaction.payment.subtotal_cents)
              - if @transaction.promo_code
                .flex-items
                  .width-70
                    %span= "Promo Code (#{@transaction.promo_code.code})"
                  .width-30.align-right
                    %span= "- #{money_to_humanized(@calculate_money.get_discount_for_all_products_cart)}"
              .flex-items
                .width-50
                  %span= "Shipping (#{@transaction.shipper.service_delivery.upcase}):"
                .width-50.align-right
                  %span= "$#{@transaction.shipper.amount}"
              .flex-items.br-bottom
                .width-50
                  %span Sales Tax:
                .width-50.align-right
                  %span= money_to_humanized(@transaction.payment.fee_cents)
              / .flex-items.br-bottom
              /   .width-70
              /     %span Movri Coverage:
              /   .width-30.align-right
              /     %span= money_to_humanized(@transaction.coverage_cents)
              .flex-items
                .width-50
                  %span.bold Total
                .width-50
                  %span.bold= money_to_humanized(@transaction.stripe_payments.last.sum_cents)
          .row
            .col-3
              %span= "<strong>#{@transaction.total_quantity} products</strong> in this order".html_safe
              .btn-link
                - if @transaction.shipper.ups?
                  = link_to "Track Package", UPS_TRACKING_PACKAGE_WEB, target: :_blank
                - else
                  = link_to "Track Package", FEDEX_TRACKING_PACKAGE_WEB, target: :_blank
        .account-list-orders
          .white-background
            .row.margin-bt-20
              .col-12.padding-10
                .flex-items.data-header.padding-5.brown-background
                  .width-15
                  .width-40
                  .width-20.center-items
                    %span QTY
                  .width-25.center-items
                    %span Price
                - @transaction.transaction_items.each do |item|
                  - listing = item.listing
                  .account-listing-item.br-bottom
                    .flex-items.padding-5
                      .width-15.center-items.padding-0
                        = image_tag listing.main_image, class: "width-100", alt: @current_community.image_alt_text
                      .width-40
                        %p.margin-0.title.cut-text= link_to listing.title, listing_path(listing)
                        %p.margin-0.sku.uppercase= "SKU: #{listing.sku ? listing.sku : 'OLLC62F'}"
                      .width-20.center-items
                        %span= item.quantity
                      .width-25.center-items
                        %span= money_to_humanized(item.price_cents)
                    / .align-right
                    /   %span= t('transactions.order_details.coverage', coverage: money_to_humanized(item.coverage_price_cents))

app/views/transactions/show.haml
= render :partial => "conversations/conversation_header", locals: {other_party: conversation_other_party}

.centered-section-wide
  = render :partial => "transactions/details", locals: {role: role, is_author: is_author, price_break_down_locals: price_break_down_locals}

  = render :partial => "conversations/messages_and_form", locals: {role: role, message_form: message_form, message_form_action: message_form_action, messages: messages}